version: '3.9'
services:
  myapp:
    build: .
    environment:
      DB_HOST: db 
      DB_PORT: 5432
      DB_USER: artem
      DB_PASSWORD: jhbv538nfjbnw92
      DB_NAME: TestDatabaseL0
      PORT: 8080
      NATS_URL: nats://nats-streaming:4222
      NATS_CLUSTER_ID: test-cluster
      NATS_CLIENT_ID: my-client-id
    depends_on:
      - nats-streaming
      - db
    ports:
      - "8080:8080"

  nats-streaming:
    image: nats-streaming:latest
    ports:
      - "4222:4222"
      - "8222:8222"

  db:
    image: postgres
    environment:
      POSTGRES_USER: artem
      POSTGRES_PASSWORD: jhbv538nfjbnw92
      POSTGRES_DB: TestDatabaseL0
    ports:
      - "5432:5432"
    volumes:
     - postgres_data:/var/lib/postgresql/data
     - ./resources/db:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
